### ISSUE TITLE
[ `Architecture` ] : Add `i18n`

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#253]
Add internationalization

**Comment by baseplate-admin** [comment]
https://youtu.be/AlJ8cGbk8ps

**Comment by baseplate-admin** [comment]
https://github.com/kaisermann/svelte-i18n/

**Comment by baseplate-admin** [comment]
@AKindWorld thoughts?

**Comment by AKindWorld** [comment]
Woah I was just thinking about this too. Good timing xD

I can already fit the language/locale switcher in the design part, no problem. In fact, I would've added it by default while designing the profile menu bar and account setting UIs. So, it can fit in without any problem.

On another note, I'll be opening a new issue soon with the completed the UI designs, so that we can have all the completed designs in one place. Also, this'll help me to add some extra necessary information to the Figma file, which may clutter it up a bit. Also might close down #115 and make the new one pinned. What do you say? 

About this current issue, let's discuss it in Discord. I think the main issue might be to get a translation team until we roll out for a wider launch.

Anyways, have a great time ahead. @baseplate-admin

**Comment by baseplate-admin** [comment]
> I can already fit the language/locale switcher in the design part, no problem. In fact, I would've added it by default while designing the profile menu bar and account setting UIs. So, it can fit in without any problem.

Seems good. 

> On another note, I'll be opening a new issue soon with the completed the UI designs, so that we can have all the completed designs in one place. Also, this'll help me to add some extra necessary information to the Figma file, which may clutter it up a bit. Also might close down https://github.com/baseplate-admin/CoreProject/issues/115 and make the new one pinned. What do you say?

Agreed. Seems very reasonable as #115 is old at this point

> About this current issue, let's discuss it in Discord. I think the main issue might be to get a translation team until we roll out for a wider launch.

Okay :D

**Comment by baseplate-admin** [comment]
@sssuneeth ,

Recon since you are the frontend engineer, whats your take on this

**Comment by sssuneeth** [comment]
Hey there! ya I take a look at that ( `i18n` ). But I didn't used that before.
Do we need to integrate it now?

**Comment by baseplate-admin** [comment]
>  Do we need to integrate it now?

It's better to have this option . Now or later

**Comment by sssuneeth** [comment]
> It's better to have this option . Now or later

Yea sure, I've this in the my list.

**Comment by baseplate-admin** [comment]
Im gonna close this. Feel free to reopen in future
