### ISSUE TITLE
[ `Design` ] : Refractor `Pagination`

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#349]
Pinging @AKindWorld,

So currently the pagination looks like this 
![image](https://user-images.githubusercontent.com/61817579/174478730-aeb2f82e-46a7-40b4-af4f-79a6650458a1.png)

Could you give me a reference to which component did you find this in ? 

Or is this a design decision to make it look a bit more unique ( This might explain why i couldn't find it in `Mantine` )

**Comment by baseplate-admin** [comment]
In the mean time please read [this ](https://discord.com/channels/@me/958266195654639646/988045119515160628)

**Comment by AKindWorld** [comment]
Hi! @baseplate-admin 

So yup, about the Pagination - it indeed isn't in Mantine (Mantine has, unfortunately, very limited choices for Pagination), so this was a somewhat unique design choice - if it isn't possible, no worries. I'll change it to something more proper.

The least I could find is something similar in Swiper - with `Autoplay`, `Pagination progress` & a lil bit of tweaking. But I do understand that it may be hard to incorporate several different libraries, which is why there's no need to worry about it. I'll just redesign it to something else - if possible though, I'd want to use a pagination system here without numbers.

And yep, I read that. No worries at all, I completely understand and it's fine by me. Honestly, it's a good idea to do that now. Also, I'm sorry for not being that much active in Discord for the last week or so.

^^

**Comment by baseplate-admin** [comment]
> So yup, about the Pagination - it indeed isn't in Mantine (Mantine has, unfortunately, very limited choices for Pagination),

Okay i see. 

>  so this was a somewhat unique design choice - if it isn't possible, no worries. I'll change it to something more proper. 

No worries, I am about to implement it. See the latest change in PR #348 

> The least I could find is something similar in Swiper - with Autoplay, Pagination progress & a lil bit of tweaking. But I do understand that it may be hard to incorporate several different libraries, which is why there's no need to worry about it. I'll just redesign it to something else - if possible though, I'd want to use a pagination system here without numbers. 

I got it :P Thanks for giving me the heads up into ideas.

> And yep, I read that. No worries at all, I completely understand and it's fine by me. Honestly, it's a good idea to do that now. Also, I'm sorry for not being that much active in Discord for the last week or so.

I thought the designer had resigned. So i was pinging you a bit too much ( i hope you didn't mind )

---

Thanks for replying i hope you have a good day :D
