### ISSUE TITLE
[ `Question` ] : What Icon library are we using? 

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject#372]
Pinging @AKindWorld

**Comment by AKindWorld** [comment]
Hmm good question. While there are lot of choices (ones that even includes making our own from scratch), I think we're better off with using the [Material Design 3 icons](https://fonts.google.com/icons). The Rounded & Filled Rounded ones fit our design scheme effortlessly, and there are a huge number of icons available too - without any plans & attribution & all that. And using a font icon library is a better choice from an UX perspective.

So yup, I think we can use it. Don't worry if an icon I used in the design isn't available there - just use something alternative since my icon library is a completely different one and is made pretty much for the design purposes only.

What're your opinions?

**Comment by baseplate-admin** [comment]
Umm i think i failed to clarify... We dont need an icon library..  I was just asking what you were using in design.. 

> So yup, I think we can use it. Don't worry if an icon I used in the design isn't available there - just use something alternative since my icon library is a completely different one and is made pretty much for the design purposes only.

Umm does it belong to any library?

> What're your opinions?

Lets keep what we have.. 😂.  Your icon design looks surprisingly good. So thats why i wondered what kind of library you were using..

**Comment by AKindWorld** [comment]
oh oops... sorry for misunderstanding

What I use are several different plugins for Figma (which all source their icons differently), the most used being Feather icons. I took a look, and they have a [website](https://feathericons.com/) & a [Github repo for the plugin](https://github.com/feathericons/figma-feather) too, but I don't think we can call it a... library? 

Also a lot of the times, I have to make changes to the icons to make sure that they look good (contrast, sizing, stroke width, color and all that), so these are mostly for the design stuff. 

But feel free to take a look anyways xD

**Comment by baseplate-admin** [comment]
> oh oops... sorry for misunderstanding

No worries. 


Okay i have my answer.. Thanks for clarifying..  Feel free to close this issue.

----

Have a good day ( or night )
